### ISSUE TITLE
I can't hide midori navigationbar

### ISSUE THREAD

**Issue by ohminy** [rupin/PiZeroMagicMirror#5]
I followed all this pjt
and finaly magicmirror shows on my monitor
but...
there is navigationbar... address
how can I hide navigationbar??

I followed this setting on autostart
xset -dpms # disable DPMS (Energy Star) features.
xset s off # disable screen saver
xset s noblank # don't blank the video device
midori -e Fullscreen -e Navigationbar your-heroku-website-url # Start Midori in Fullscreen mode, without a Navigation bar, and load the URL.

**Comment by rupin** [comment]
Can you post a photo?

**Comment by ohminy** [comment]
there is navigationbar
I cant remove that...
now I'm trying xdotool... but not clear yet..
![20230405_003953](https://user-images.githubusercontent.com/46082430/229845556-d245c75e-9de7-43d1-bdc2-3560a67f9087.jpg)

**Comment by rupin** [comment]
I had this same problem. I used to login once from VNC server and just click the mouse on the screen. That worked for me.

I also remember changing this line 

`midori -e Fullscreen -e Navigationbar` 

to  

`midori -e Fullscreen`

And running it once. 

Then reverting back to 

`midori -e Fullscreen -e Navigationbar` 

between reboots.
